# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/toy_adt/all/toy_adt.rbi
#
# toy_adt-0.1.0

module ToyAdt
  extend ToyAdt::PublicApi
end
